# Generated by Django 2.0.5 on 2018-12-16 17:25

from django.db import migrations, models
import django.db.models.deletion
import eventbus.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMessage',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('message', models.BinaryField()),
                ('processed', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelEventMessage',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('message', models.BinaryField()),
                ('processed', models.DateTimeField()),
                ('object_id', models.PositiveIntegerField()),
                ('event_type',
                 models.CharField(
                     blank=True,
                     choices=[(eventbus.models.ModelEventTypeChoice(
                         'Model Object Creation'), 'Model Object Creation'),
                              (eventbus.models.ModelEventTypeChoice(
                                  'Model Object Modification'),
                               'Model Object Modification'),
                              (eventbus.models.ModelEventTypeChoice(
                                  'Model Object Deletion'),
                               'Model Object Deletion')],
                     max_length=1,
                     null=True)),
                ('content_type',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
