# Generated by Django 2.0.5 on 2018-12-16 18:09

from django.db import migrations, models
import django.db.models.deletion
import eventbus.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('processed', models.DateTimeField()),
                ('success', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsumerModelEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('event_type', models.CharField(choices=[(eventbus.models.ModelEventTypeChoice('Model Object Creation'), 'Model Object Creation'), (eventbus.models.ModelEventTypeChoice('Model Object Modification'), 'Model Object Modification'), (eventbus.models.ModelEventTypeChoice('Model Object Deletion'), 'Model Object Deletion')], max_length=1)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventbus.ConsumerEvent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProducerEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('processed', models.DateTimeField()),
                ('success', models.BooleanField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventbus.EventTopic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProducerModelEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('event_type', models.CharField(choices=[(eventbus.models.ModelEventTypeChoice('Model Object Creation'), 'Model Object Creation'), (eventbus.models.ModelEventTypeChoice('Model Object Modification'), 'Model Object Modification'), (eventbus.models.ModelEventTypeChoice('Model Object Deletion'), 'Model Object Deletion')], max_length=1)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventbus.ProducerEvent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='consumerevent',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventbus.EventTopic'),
        ),
    ]
